use_frameworks!

target 'BGSProgressMonitor_Example' do
  pod 'BGSProgressMonitor', :path => '../'

  target 'BGSProgressMonitor_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  end
end
